#!/bin/bash

. "bin/config"

set -o errexit
set -o pipefail

NOW=$(date +%s)

# update the script as to ensure new image sha 
sed -e "s/REPLACE/${NOW}/" tests/hello-template > tests/hello

TEST_IMAGE_URI="${IMAGE_REG}/tester:v1.2.${NOW}"
echo $TEST_IMAGE_URI

# Build and push image
docker build -f tests/Dockerfile \
             -t $TEST_IMAGE_URI \
             --label artomator-sbom=true \
             --label artomator-vuln=true \
             --platform linux/amd64 .
docker push $TEST_IMAGE_URI

TEST_IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' $TEST_IMAGE_URI)
echo "IMAGE_SHA: ${TEST_IMAGE_SHA}"

# parse new event data
EVENT_DATA=$(sed -e "s=IMAGE_SHA=${TEST_IMAGE_SHA}=g" tests/event-template.json)
EVENT_ENCODED_DAT=$(echo -ne ${EVENT_DATA} | base64)

# update message 
sed -e "s/EVENT_DATA/${EVENT_ENCODED_DAT}/g" tests/message-template.json > tests/message.json


