#!/bin/bash

. "bin/config"

set -o errexit
set -o pipefail

NOW=$(date +%s)

# update the script as to ensure new image sha 
sed -e "s/REPLACE/${NOW}/" tests/hello-template > tests/hello

TEST_IMAGE_URI="${IMAGE_REG}/tester:v1.2.${NOW}"
echo $TEST_IMAGE_URI

# Build and push image
docker build -f tests/Dockerfile \
             -t $TEST_IMAGE_URI \
             --label sbom=true \
             --label vuln=true \
             --platform linux/amd64 .
docker push $TEST_IMAGE_URI

IMAGE_SHA=$(docker inspect --format='{{index .RepoDigests 0}}' $TEST_IMAGE_URI)
echo "IMAGE_SHA: ${IMAGE_SHA}"
