#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -o errexit
set -o pipefail

DIRTY_IMG="$IMAGE_URI"

# Build and push image
docker build -f deployment/Dockerfile \
             --build-arg VERSION="${VERSION}" \
             --platform linux/amd64 \
             -t $DIRTY_IMG \
             .
# docker push $DIRTY_IMG
