#!/bin/bash

DIR="$(dirname "$0")"
. "${DIR}/config"

set -o errexit
set -o pipefail

echo "commented cause terraform"

# gcloud artifacts repositories delete $ROOT_NAME --location $REGION -q
# gcloud iam service-accounts delete $SA_EMAIL -q
# gcloud pubsub subscriptions delete gcr-sub -q
# gcloud pubsub topics delete gcr -q
# gcloud run services delete $ROOT_NAME --region $REGION -q
# gcloud redis instances delete $ROOT_NAME --region $REGION -q
# gcloud compute networks vpc-access connectors delete "${ROOT_NAME}-connector" --region $REGION -q