#!/bin/bash

# validation 
gcloud=$(which gcloud)   || ( echo "gcloud not found" && exit 1 )

if [[ -z "${PROJECT_ID}" ]]; then
  echo "PROJECT_ID not set, 'export PROJECT_ID=YOUR-PROJECT'."
  exit 1
fi;

ACCOUNT=$(gcloud auth list --filter=status:ACTIVE --format="value(account)")
if [[ -z "${ACCOUNT}" ]]; then
  echo "Run 'gcloud auth login' to authenticate on GCP before running this script."
  exit 1
fi;

if [[ -z "${REGION}" ]]; then
  export REGION="us-west1"
fi;

# derived vars 
export PROJECT_NUMBER="$(gcloud projects describe "${PROJECT_ID}" --format='value(projectNumber)')"

# used as a root for all things created by this app
export ROOT_NAME="artomator"

# derived values
export VERSION=$(cat .version)
export COMMIT=$(git rev-parse --short HEAD)
