#!/bin/bash

. "tools/config"

set -o errexit
set -o pipefail


echo "
ROOT_NAME  : $ROOT_NAME
REGION     : $REGION
VERSION    : $VERSION
SA_NAME    : $SA_NAME
SA_EMAIL   : $SA_EMAIL
KEY_NAME   : $KEY_NAME
KEY_PATH   : $KEY_PATH
SIGN_KEY   : $SIGN_KEY
IMAGE_REG  : $IMAGE_REG
IMAGE_URI  : $IMAGE_URI
GCS_BUCKET : $GCS_BUCKET
"